version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: retirement_snapshot
    ports:
      - 5438:5432

  data_migration:
    build:
      context: .
      dockerfile: .ci/dockerfiles/locals/kamafi-retirement-snapshot-data-migrations.dockerfile
    environment:
      RetirementSnapshotDb__Host: postgres
      RetirementSnapshotDb__Username: admin
      RetirementSnapshotDb__Password: admin
      RetirementSnapshotDb__DatabaseName: retirement_snapshot
    depends_on:
      - postgres

  background:
    build:
      context: .
      dockerfile: .ci/dockerfiles/locals/kamafi-retirement-snapshot-background.dockerfile
    depends_on:
      - data_migration
    environment:
      BackgroundServiceOptions__Period: 3