name: build-data-migrations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_kamafi_retirement_snapshot_data_migrations:
    uses: ./.github/workflows/build-base.yml
    with:
      configuration: release
      project_file: KamaFi.Retirement.Snapshot.Data.Migrations/KamaFi.Retirement.Snapshot.Data.Migrations.csproj
      output_path: app/publish

  build_kamafi_retirement_snapshot_data_migrations_container:
    needs: build_kamafi_retirement_snapshot_data_migrations
    uses: ./.github/workflows/build-container-base.yml
    with:
      configuration: release
      project_file: KamaFi.Retirement.Snapshot.Data.Migrations/KamaFi.Retirement.Snapshot.Data.Migrations.csproj
      output_path: app/publish
      dockerfile: kamafi-retirement-snapshot-data-migrations.dockerfile
      tag: kamafi-retirement-snapshot-data-migrations:latest